small = [
    /free/g,
    /[Nn]itro(?! [Mm]an)/g,
    /[Cc][Ss]:? ?[Gg][Oo]/g,
    /trade/g,
    /skins/g,
    /knife/g,
    /\S+\.[^.]+\/\S*/g,
    /[Ss]team/g,
    /STEAM/g,
    /@everyone/g,
    /[Aa]irdrop/g,
    /[Dd]iscord.+?subscription/g,
    /[Dd]istribut(ion|ed)/g,
]

full = [
    /([Cc][Ss]:? ?[Gg][Oo]|skins).{50,}(profiles|token)/,
    /[Dd]on\u0027t be (greedy|modest) and take few/,
    /[Cc][Ss]:? ?[Gg][Oo].{3,}(giving away|give everything|trade)/,
    /([Hh]ello|[Hh]i).{20,}i will give a.{3,}knife/,
    /@everyone.+([Ss]team|STEAM|[Cc][Ss]:? ?[Gg][Oo]|bit\.ly|[Dd]iscord( |-)[Nn]itro(?! [Mm]an)|🆓|hurry up)/,
    /Free [3-9] Months of Discord( |-)Nitro.+http/,
    /([Ss]team|STEAM|[Cc][Ss]:? ?[Gg][Oo]|bit\.ly|[Dd]iscord( |-)[Nn]itro (?![Mm]an)|🆓|hurry up).+@everyone/,
    /first.{3,15}who send a trade/,
    /i abandoned the cop and decided to distribute/,
    /store[\.\-](?!steampowered|playstation|hp)[^.]+?\.com\/app\/\d+/,
    /([Hh]i|[Hh]ello),? (bro|friend|guys), today I am leaving this (fucking)? game (with a bunch of cheaters|.+skins)/,
    /([Hh]i|[Hh]ello),? (bro|friend|guys), I left [Cc][Ss]:? ?[Gg][Oo] because.+fucking cheaters in every game/,
    /(skins?\.?|trade|knife|sale|Rust).+(((i\.)?imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?)?.+https?:\/\/s(?!teamcommunity)[^.]+?\.com\/\w{3,12}(=[a-z0-9]{6,8}=\?[0-9]{1,}|\/[0-9]{15,}|\/([a-z0-9]{2,3}\/)?\?[a-z]{5,10}=[0-9]{6,14}&[a-z]{4,6}=-?\w{4,12}|\/[0-9]{5,8}\/\w{4,8}\/)$/,
    /dlscord(app)?\.(codes|shop|wiki)/,
    /(?!discord\.com)\/billing\/promotions\/[a-zA-Z0-9]{15,}\/$/,
    /(wowfnatic|giveawaynitro)\.(site|com)/,
    /(([Dd]iscord( |-)[Nn]itro|free|[Ss]team).+airdrop|[Aa]irdrop.+([Dd]iscord( |-)[Nn]itro|free|[Ss]team))/,
    /((i\.)?imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?.+(free|([Dd]iscord)?( |-)[Nn]itro(?! [Mm]an))[^.]+?(for [Ff]ree|([Dd]iscord)?( |-)[Nn]itro(?! [Mm]an))/,
    /((i\.)?imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?.+(bit\.ly|discord\.ink)/,
    /[Hh]ey cuz!!.+[Ss]team/,
    /[Dd]iscord( |-)[Nn]itro.+[Oo]ffer (ends|is valid).+(January|February|March|April|May|June|July|August|September|October|November|December) [1-3]?\d(st|nd|rd|th)?.+202[1-3]/,
    /[Gg]et [1-9] months of [Dd]iscord [Nn]itro.+Personalize your profile/,
    /skins?.+\([^.]+?(i\.)?(imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?\).+everyone/,
    /(ч|л|э|п|и|б|д|ц).+(@everyone|http)/,
    /[Ff]ree ([Dd]iscord( |-))?[Nn]itro.+[1-9] [Mm]onths?/,
    /d(?!iscor)[a-z]{5}d(app)?\.[a-z]{2,4}\/[a-z0-9]{3,5}\/\w{7,10}$/,
    /(cl[il]scord|d[il]scorcl|cl[il]scorcl)/,
    /\.[a-z]{2,4}\/nitro\/steam/,
    /[Ss]team.+[Dd]iscord( |-)[Nn]itro/,
    /[Ss]ee here bro >>>/,
    /[Hh]ot and beautiful girls.+sex/,
    /[Hh]i bro!.+([Hh]ot|[Bb]eautiful).+girls/,
    /[Gg]irls.+wats sex/,
    /([Ss]team|[Dd]iscord).+bit\.ly/,
    /2014 Cobblestone Souvenir Package/,
    /[Gg]et [1-9] months of [Dd]iscord [Nn]itro (for)? free/,
    /\.(xyz|ru|link)\/(gift|nitro|steam)/,
    /[Dd]iscord ([Nn]itro|NITRO) with [Ss]team/,
    /get.+[Nn]itro(?! [Mm]an).+free/,
    /[Ss]team.+[Nn]itro(?! [Mm]an)/,
    /([Ss]team|[Nn]itro(?! [Mm]an)).+([Ii] already got mine|[Ii].+already received this)/,
    /([Ii] already got mine|[Ii].+already received this).+([Ss]team|[Nn]itro(?! [Mm]an))/,
    /\.ru\.com/,
    /[Nn]itro.+promotion.+[Ss]team/,
    /([Hh]i|[Hh]ello).+[Yy]ou won [Dd]iscord [Nn]itro/,
    /nitro\.(com|link)/,
    /[Dd]iscord [Nn](itro|ITRO).+free.+https?:\/\//,
    /free.+[Dd]iscord [Nn](itro|ITRO).+https?:\/\//,
    /[Ff]ree [Nn]itro(?! [Mm]an).+https?:\/\//,
    /confirm the all exchanges/,
    /take all what you want/,
    /Customize your profile, share your screen in HD, update your emoji and more!.+https?:\/\//,
    /Personalize your profile, screen share in HD, upgrade your emojis, and more!.+https?:\/\//,
    /[Ss]team is giving away [1-9] [Mm]onths of [Dd]iscord [Nn]itro/,
    /[Ss]team ?give ?[Nn]itro/,
    /(([Hh]i|[Hh]ello),? (bro|friend|guys)(,|!)|free|[Nn]itro(?! [Mm]an)|[Ss]team).+https?:\/\/d(?!iscord)[il]scou?r(d|cl|b)(gift)?\.[a-z]{2,5}(\.uk)?/,
    /(([Hh]i|[Hh]ello),? (bro|friend|guys)(,|!)|free|[Nn]itro(?! [Mm]an)|[Ss]team).+https?:\/\/cliscou?r(d|cl|b)(gift)?\.[a-z]{2,5}(\.uk)?/,
    /https?:\/\/([a-z]{6,9}|free|gifts)-?nitro(ss?|i)?\.[a-z]{2,5}(\.uk|.com)?.{5,12}( @everyone)?$/,
    /some [Jj]apanese candy/,
    /bonsaignw/,
    /[Dd]iscord giving [1-9] [Mm]onths? of [Ff]ree [Nn]itro/,
    /[Dd]on\u0027t thank :call_me: ?$/,
    /hurry up.+([Nn]itro(?! [Mm]an)|trade|skin|[Cc][Ss]:? ?[Gg][Oo]).+https?:\/\//,
    /([Nn]itro(?! [Mm]an)|trade|skin|[Cc][Ss]:? ?[Gg][Oo]).+hurry up.+https?:\/\//,
    /nitro\sof\sdiscord\sfreebie/,
    /🎮.+?(https:\/\/)?🆓.+?(https:\/\/)⚠️/,
    /[Ss]team has teamed up with [Dd]iscord/,
    /have time to pick up too before the distribution is over/,
    /[Dd]iscord [Nn](?!itr)[a-z]{3}o.+https?:\/\//,
]

module.exports = {
    small,
    full
}
