const small = [
	/free/g,
	/[Nn]itro(?! [Mm]an)/g,
	/[Cc][Ss]:? ?[Gg][Oo]/g,
	/trade/g,
	/skins/g,
	/knife/g,
	/\S+\.[^.]+\/\S*/g,
	/[Ss]team/g,
	/STEAM/g,
	/@everyone/g,
	/[Aa]irdrop/g
];

const full = [
/* 0*/      /([Cc][Ss]:? ?[Gg][Oo]|skins).{50,}(profiles|token)/,
/* 1*/      /[Dd]on\u0027t be (greedy|modest) and take few/,
/* 2*/      /[Cc][Ss]:? ?[Gg][Oo].{3,}(giving away|give everything|trade)/,
/* 3*/      /([Hh]ello|[Hh]i).{20,}i will give a.{3,}knife/,
/* 4*/      /@everyone.+([Ss]team|STEAM|[Cc][Ss]:? ?[Gg][Oo]|bit\.ly|[Dd]iscord( |-)[Nn]itro(?! [Mm]an)|🆓|hurry up)/,
/* 5*/      /Free [3-9] Months of Discord( |-)Nitro.+http/,
/* 6*/      /([Ss]team|STEAM|[Cc][Ss]:? ?[Gg][Oo]|bit\.ly|[Dd]iscord( |-)[Nn]itro (?![Mm]an)|🆓|hurry up).+@everyone/,
/* 7*/      /first.{3,15}who send a trade/,
/* 8*/      /i abandoned the cop and decided to distribute/,
/* 9*/      /store[\.\-](?!steampowered|playstation|hp)[^.]+?\.com\/app\/\d+/,
/*10*/      /([Hh]i|[Hh]ello),? (bro|friend|guys), today I am leaving this (fucking)? game (with a bunch of cheaters|.+skins)/,
/*11*/      /([Hh]i|[Hh]ello),? (bro|friend|guys), I left [Cc][Ss]:? ?[Gg][Oo] because.+fucking cheaters in every game/,
/*12*/      /(skins?\.?|trade|knife|sale|Rust).+(((i\.)?imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?)?.+https?:\/\/s(?!teamcommunity)[^.]+?\.com\/\w{3,12}(=[a-z0-9]{6,8}=\?[0-9]{1,}|\/[0-9]{15,}|\/([a-z0-9]{2,3}\/)?\?[a-z]{5,10}=[0-9]{6,14}&[a-z]{4,6}=-?\w{4,12}|\/[0-9]{5,8}\/\w{4,8}\/)$/,
/*13*/      /dlscord(app)?\.(codes|shop|wiki)/,
/*14*/      /(?!discord\.com)\/billing\/promotions\/[a-zA-Z0-9]{15,}\/$/,
/*15*/      /(wowfnatic|giveawaynitro)\.(site|com)/,
/*16*/      /(([Dd]iscord( |-)[Nn]itro|free|[Ss]team).+airdrop|[Aa]irdrop.+([Dd]iscord( |-)[Nn]itro|free|[Ss]team))/,
/*17*/      /((i\.)?imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?.+(free|([Dd]iscord)?( |-)[Nn]itro(?! [Mm]an))[^.]+?(for [Ff]ree|([Dd]iscord)?( |-)[Nn]itro(?! [Mm]an))/,
/*18*/      /((i\.)?imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?.+(bit\.ly|discord\.ink)/,
/*19*/      /[Hh]ey cuz!!.+[Ss]team/,
/*20*/      /[Dd]iscord( |-)[Nn]itro.+[Oo]ffer (ends|is valid).+(January|February|March|April|May|June|July|August|September|October|November|December) [1-3]?\d(st|nd|rd|th)?.+202[1-3]/,
/*21*/      /[Gg]et [1-9] months of [Dd]iscord [Nn]itro.+Personalize your profile/,
/*22*/      /skins?.+\([^.]+?(i\.)?(imgur\.com|ibb\.co)\/(a\/)?\w{6,8}(\.png|\.jpg)?\).+everyone/,
/*23*/      /(ч|л|э|п|и|б|д|ц).+(@everyone|http)/,
/*24*/      /[Ff]ree ([Dd]iscord( |-))?[Nn]itro.+[1-9] [Mm]onths?/,
/*25*/      /d(?!iscor)[a-z]{5}d(app)?\.[a-z]{2,4}\/[a-z0-9]{3,5}\/\w{7,10}$/,
/*26*/      /(cl[il]scord|d[il]scorcl|cl[il]scorcl)/,
/*27*/      /\.[a-z]{2,4}\/nitro\/steam/,
/*28*/      /[Ss]team.+[Dd]iscord( |-)[Nn]itro/,
/*29*/      /[Ss]ee here bro >>>/,
/*30*/      /[Hh]ot and beautiful girls.+sex/,
/*31*/      /[Hh]i bro!.+([Hh]ot|[Bb]eautiful).+girls/,
/*32*/      /[Gg]irls.+wats sex/,
/*33*/      /([Ss]team|[Dd]iscord).+bit\.ly/,
/*34*/      /2014 Cobblestone Souvenir Package/,
/*35*/      /[Gg]et [1-9] months of [Dd]iscord [Nn]itro (for)? free/,
/*36*/      /\.(xyz|ru|link)\/(gift|nitro|steam)/,
/*37*/      /[Dd]iscord ([Nn]itro|NITRO) with [Ss]team/,
/*38*/      /get.+[Nn]itro(?! [Mm]an).+free/,
/*39*/      /[Ss]team.+[Nn]itro(?! [Mm]an)/,
/*40*/      /([Ss]team|[Nn]itro(?! [Mm]an)).+([Ii] already got mine|[Ii].+already received this)/,
/*41*/      /([Ii] already got mine|[Ii].+already received this).+([Ss]team|[Nn]itro(?! [Mm]an))/,
/*42*/      /\.ru\.com/,
/*43*/      /[Nn]itro.+promotion.+[Ss]team/,
/*44*/      /([Hh]i|[Hh]ello).+[Yy]ou won [Dd]iscord [Nn]itro/,
/*45*/      /nitro\.(com|link)/,
/*46*/      /[Dd]iscord [Nn](itro|ITRO).+free.+https?:\/\//,
/*47*/      /free.+[Dd]iscord [Nn](itro|ITRO).+https?:\/\//,
/*48*/      /[Ff]ree [Nn]itro(?! [Mm]an).+https?:\/\//,
/*49*/      /confirm the all exchanges/,
/*50*/      /take all what you want/,
/*51*/      /Customize your profile, share your screen in HD, update your emoji and more!.+https?:\/\//,
/*52*/      /Personalize your profile, screen share in HD, upgrade your emojis, and more!.+https?:\/\//,
/*53*/      /[Ss]team is giving away [1-9] [Mm]onths of [Dd]iscord [Nn]itro/,
/*54*/      /[Ss]team ?give ?[Nn]itro/,
/*55*/      /(([Hh]i|[Hh]ello),? (bro|friend|guys)(,|!)|free|[Nn]itro(?! [Mm]an)|[Ss]team).+https?:\/\/d(?!iscord)[il]scou?r(d|cl|b)(gift)?\.[a-z]{2,5}(\.uk)?/,
/*56*/      /(([Hh]i|[Hh]ello),? (bro|friend|guys)(,|!)|free|[Nn]itro(?! [Mm]an)|[Ss]team).+https?:\/\/cliscou?r(d|cl|b)(gift)?\.[a-z]{2,5}(\.uk)?/,
/*57*/      /https?:\/\/([a-z]{6,9}|free|gifts)-?nitro(ss?|i)?\.[a-z]{2,5}(\.uk|.com)?.{5,12}( @everyone)?$/,
/*58*/      /some [Jj]apanese candy/,
/*59*/      /bonsaignw/,
/*60*/      /[Dd]iscord giving [1-9] [Mm]onths? of [Ff]ree [Nn]itro/,
/*61*/      /[Dd]on\u0027t thank :call_me: ?$/,
/*62*/      /hurry up.+([Nn]itro(?! [Mm]an)|trade|skin|[Cc][Ss]:? ?[Gg][Oo]).+https?:\/\//,
/*63*/      /([Nn]itro(?! [Mm]an)|trade|skin|[Cc][Ss]:? ?[Gg][Oo]).+hurry up.+https?:\/\//
];

module.exports = {
    small,
    full
}
